-- Phase 2 of account setup: run only after COVID_PROJECT_ADMIN and
-- COVID_APP_ROLE have been granted to the deployment user.

USE ROLE COVID_PROJECT_ADMIN;

CREATE SCHEMA IF NOT EXISTS COVID_ANALYTICS.RAW
COMMENT = 'Original external and imported data';

CREATE SCHEMA IF NOT EXISTS COVID_ANALYTICS.STAGING
COMMENT = 'Cleaned and transformed data';

CREATE SCHEMA IF NOT EXISTS COVID_ANALYTICS.MARTS
COMMENT = 'Final analytical tables and views';

CREATE SCHEMA IF NOT EXISTS COVID_ANALYTICS.APP
COMMENT = 'Objects used by the API and dashboard';

GRANT USAGE ON SCHEMA COVID_ANALYTICS.MARTS
TO ROLE COVID_APP_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA COVID_ANALYTICS.MARTS
TO ROLE COVID_APP_ROLE;

GRANT SELECT ON FUTURE TABLES IN SCHEMA COVID_ANALYTICS.MARTS
TO ROLE COVID_APP_ROLE;

GRANT SELECT ON ALL VIEWS IN SCHEMA COVID_ANALYTICS.MARTS
TO ROLE COVID_APP_ROLE;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA COVID_ANALYTICS.MARTS
TO ROLE COVID_APP_ROLE;

USE WAREHOUSE COVID_WH;

USE DATABASE COVID_ANALYTICS;

USE SCHEMA RAW;

-- Expected context: COVID_PROJECT_ADMIN | COVID_WH | COVID_ANALYTICS | RAW.
SELECT
    CURRENT_ROLE() AS CURRENT_ROLE,
    CURRENT_WAREHOUSE() AS CURRENT_WAREHOUSE,
    CURRENT_DATABASE() AS CURRENT_DATABASE,
    CURRENT_SCHEMA() AS CURRENT_SCHEMA;

SHOW SCHEMAS IN DATABASE COVID_ANALYTICS;
