-- Run each statement separately in a Snowsight SQL worksheet.
-- ACCOUNTADMIN is required to bootstrap the resource monitor, warehouse,
-- database, and least-privilege project role.

USE ROLE ACCOUNTADMIN;

CREATE RESOURCE MONITOR IF NOT EXISTS COVID_PROJECT_MONITOR
WITH
    CREDIT_QUOTA = 5
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 50 PERCENT DO NOTIFY
        ON 80 PERCENT DO SUSPEND
        ON 100 PERCENT DO SUSPEND_IMMEDIATE;

CREATE WAREHOUSE IF NOT EXISTS COVID_WH
WITH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for the COVID-19 Bootcamp project';

-- Run this even when COVID_WH already existed.
ALTER WAREHOUSE COVID_WH
SET RESOURCE_MONITOR = COVID_PROJECT_MONITOR;

CREATE DATABASE IF NOT EXISTS COVID_ANALYTICS
COMMENT = 'Database for the COVID-19 analytics project';

CREATE ROLE IF NOT EXISTS COVID_PROJECT_ADMIN
COMMENT = 'Owns and operates the COVID-19 analytics project objects';

-- A user with SYSADMIN can inherit the project role through this hierarchy.
GRANT ROLE COVID_PROJECT_ADMIN TO ROLE SYSADMIN;

GRANT USAGE, OPERATE, MONITOR ON WAREHOUSE COVID_WH
TO ROLE COVID_PROJECT_ADMIN;

GRANT USAGE, CREATE SCHEMA ON DATABASE COVID_ANALYTICS
TO ROLE COVID_PROJECT_ADMIN;

-- The Marketplace database must already be installed under this name.
GRANT USAGE ON DATABASE COVID19_EPIDEMIOLOGICAL_DATA
TO ROLE COVID_PROJECT_ADMIN;

GRANT USAGE ON SCHEMA COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC
TO ROLE COVID_PROJECT_ADMIN;

GRANT SELECT ON ALL TABLES IN SCHEMA
    COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC
TO ROLE COVID_PROJECT_ADMIN;

USE ROLE COVID_PROJECT_ADMIN;

CREATE SCHEMA IF NOT EXISTS COVID_ANALYTICS.RAW
COMMENT = 'Original external and imported data';

CREATE SCHEMA IF NOT EXISTS COVID_ANALYTICS.STAGING
COMMENT = 'Cleaned and transformed data';

CREATE SCHEMA IF NOT EXISTS COVID_ANALYTICS.MARTS
COMMENT = 'Final analytical tables and views';

CREATE SCHEMA IF NOT EXISTS COVID_ANALYTICS.APP
COMMENT = 'Objects used by the API and dashboard';

USE WAREHOUSE COVID_WH;

USE DATABASE COVID_ANALYTICS;

USE SCHEMA RAW;

-- Expected context: COVID_PROJECT_ADMIN | COVID_WH | COVID_ANALYTICS | RAW.
SELECT
    CURRENT_ROLE() AS CURRENT_ROLE,
    CURRENT_WAREHOUSE() AS CURRENT_WAREHOUSE,
    CURRENT_DATABASE() AS CURRENT_DATABASE,
    CURRENT_SCHEMA() AS CURRENT_SCHEMA;

SHOW RESOURCE MONITORS LIKE 'COVID_PROJECT_MONITOR';

SHOW WAREHOUSES LIKE 'COVID_WH';

SHOW DATABASES LIKE 'COVID_ANALYTICS';

SHOW SCHEMAS IN DATABASE COVID_ANALYTICS;

-- Use PYTHON_ACCOUNT_IDENTIFIER as SNOWFLAKE_ACCOUNT in .env.
SELECT
    CURRENT_ORGANIZATION_NAME() AS ORGANIZATION_NAME,
    CURRENT_ACCOUNT_NAME() AS ACCOUNT_NAME,
    CURRENT_ORGANIZATION_NAME()
        || '-'
        || CURRENT_ACCOUNT_NAME() AS PYTHON_ACCOUNT_IDENTIFIER,
    CURRENT_ACCOUNT() AS ACCOUNT_LOCATOR,
    CURRENT_REGION() AS REGION,
    CURRENT_USER() AS USER_NAME;
