-- Prerequisite: add the free Marketplace dataset to the account under the
-- database name COVID19_EPIDEMIOLOGICAL_DATA.
-- Run each statement separately in a Snowsight SQL worksheet.

USE ROLE COVID_PROJECT_ADMIN;

USE WAREHOUSE COVID_WH;

-- Discover the Marketplace objects.
SELECT
    TABLE_NAME,
    TABLE_TYPE
FROM COVID19_EPIDEMIOLOGICAL_DATA.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'PUBLIC'
ORDER BY TABLE_NAME;

SHOW TABLES IN SCHEMA COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC;

SHOW VIEWS IN SCHEMA COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC;

-- Confirm that DATE, COUNTRY_REGION, CASES, DEATHS, and ISO3166_1 exist.
DESC TABLE COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.ECDC_GLOBAL;

SELECT
    COLUMN_NAME,
    DATA_TYPE,
    ORDINAL_POSITION
FROM COVID19_EPIDEMIOLOGICAL_DATA.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'PUBLIC'
  AND TABLE_NAME = 'ECDC_GLOBAL'
ORDER BY ORDINAL_POSITION;

-- Preview the source.
SELECT *
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.ECDC_GLOBAL
LIMIT 20;

SELECT
    DATE,
    COUNTRY_REGION,
    CASES,
    DEATHS
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.ECDC_GLOBAL
ORDER BY COUNTRY_REGION, DATE
LIMIT 100;

-- Dataset coverage.
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT COUNTRY_REGION) AS COUNTRY_COUNT,
    MIN(DATE) AS FIRST_DATE,
    MAX(DATE) AS LAST_DATE
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.ECDC_GLOBAL;

-- No result means there are no duplicate country-date combinations.
SELECT
    COUNTRY_REGION,
    DATE,
    COUNT(*) AS ROWS_PER_COUNTRY_DATE
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.ECDC_GLOBAL
GROUP BY
    COUNTRY_REGION,
    DATE
HAVING COUNT(*) > 1
ORDER BY ROWS_PER_COUNTRY_DATE DESC
LIMIT 50;

-- Missing-value counts and percentages.
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(COUNTRY_REGION IS NULL) AS MISSING_COUNTRY,
    COUNT_IF(DATE IS NULL) AS MISSING_DATE,
    COUNT_IF(CASES IS NULL) AS MISSING_CASES,
    COUNT_IF(DEATHS IS NULL) AS MISSING_DEATHS,
    ROUND(
        100.0 * COUNT_IF(CASES IS NULL) / NULLIF(COUNT(*), 0),
        2
    ) AS MISSING_CASES_PERCENT,
    ROUND(
        100.0 * COUNT_IF(DEATHS IS NULL) / NULLIF(COUNT(*), 0),
        2
    ) AS MISSING_DEATHS_PERCENT
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.ECDC_GLOBAL;

-- Negative daily values represent source corrections.
SELECT
    DATE,
    COUNTRY_REGION,
    CASES,
    DEATHS
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.ECDC_GLOBAL
WHERE CASES < 0
   OR DEATHS < 0
ORDER BY DATE, COUNTRY_REGION;

-- CASES and DEATHS rise and fall between dates, confirming daily values.
-- Do not derive new cases with CASES - LAG(CASES).
SELECT
    DATE,
    COUNTRY_REGION,
    CASES,
    DEATHS
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.ECDC_GLOBAL
WHERE COUNTRY_REGION = 'Latvia'
ORDER BY DATE
LIMIT 50;
