-- Run after 02_create_country_mapping.sql.
-- Run each statement separately in a Snowsight SQL worksheet.

USE ROLE COVID_PROJECT_ADMIN;

USE WAREHOUSE COVID_WH;

CREATE OR REPLACE VIEW
    COVID_ANALYTICS.STAGING.COVID_COUNTRY_DAILY
AS
WITH NORMALIZED_SOURCE AS (
    SELECT
        COALESCE(
            mapping.NORMALIZED_COUNTRY_NAME,
            REPLACE(TRIM(source.COUNTRY_REGION), '_', ' ')
        ) AS COUNTRY,
        COALESCE(
            mapping.NORMALIZED_ISO2,
            IFF(
                LENGTH(TRIM(source.ISO3166_1)) = 2,
                UPPER(TRIM(source.ISO3166_1)),
                NULL
            )
        ) AS COUNTRY_ISO2,
        COALESCE(
            mapping.NORMALIZED_ISO3,
            IFF(
                LENGTH(TRIM(source.ISO3166_1)) = 3,
                UPPER(TRIM(source.ISO3166_1)),
                NULL
            )
        ) AS COUNTRY_ISO3,
        source.DATE::DATE AS REPORT_DATE,
        COALESCE(source.CASES, 0)::NUMBER AS CASES,
        COALESCE(source.DEATHS, 0)::NUMBER AS DEATHS,
        mapping.SOURCE_COUNTRY_NAME IS NOT NULL AS MAPPING_APPLIED,
        COALESCE(mapping.EXPECTED_POPULATION_MATCH, TRUE)
            AS EXPECTED_POPULATION_MATCH
    FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.ECDC_GLOBAL AS source
    LEFT JOIN COVID_ANALYTICS.RAW.COUNTRY_CODE_MAPPING AS mapping
        ON UPPER(TRIM(source.COUNTRY_REGION))
            = UPPER(mapping.SOURCE_COUNTRY_NAME)
       AND COALESCE(UPPER(TRIM(source.ISO3166_1)), '')
            = COALESCE(mapping.SOURCE_COUNTRY_CODE, '')
    WHERE source.COUNTRY_REGION IS NOT NULL
      AND source.DATE IS NOT NULL
),
DAILY AS (
    SELECT
        COUNTRY,
        COUNTRY_ISO2,
        COUNTRY_ISO3,
        COALESCE(
            COUNTRY_ISO3,
            COUNTRY_ISO2,
            UPPER(COUNTRY)
        ) AS LOCATION_KEY,
        REPORT_DATE,
        SUM(CASES) AS NEW_CASES_RAW,
        SUM(DEATHS) AS NEW_DEATHS_RAW,
        COUNT(*) AS SOURCE_ROW_COUNT,
        BOOLOR_AGG(MAPPING_APPLIED) AS MAPPING_APPLIED,
        BOOLOR_AGG(EXPECTED_POPULATION_MATCH)
            AS EXPECTED_POPULATION_MATCH
    FROM NORMALIZED_SOURCE
    GROUP BY 1, 2, 3, 4, 5
)
SELECT
    COUNTRY,
    COUNTRY_ISO2,
    COUNTRY_ISO3,
    LOCATION_KEY,
    REPORT_DATE,
    NEW_CASES_RAW,
    NEW_DEATHS_RAW,
    SUM(NEW_CASES_RAW) OVER (
        PARTITION BY LOCATION_KEY
        ORDER BY REPORT_DATE
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS CASES_CUMULATIVE,
    SUM(NEW_DEATHS_RAW) OVER (
        PARTITION BY LOCATION_KEY
        ORDER BY REPORT_DATE
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS DEATHS_CUMULATIVE,
    NEW_CASES_RAW < 0 AS HAS_NEGATIVE_CASE_CORRECTION,
    NEW_DEATHS_RAW < 0 AS HAS_NEGATIVE_DEATH_CORRECTION,
    SOURCE_ROW_COUNT,
    MAPPING_APPLIED,
    EXPECTED_POPULATION_MATCH
FROM DAILY;

SELECT *
FROM COVID_ANALYTICS.STAGING.COVID_COUNTRY_DAILY
ORDER BY COUNTRY, REPORT_DATE
LIMIT 100;

-- Daily values should rise and fall; cumulative values generally increase.
SELECT
    REPORT_DATE,
    NEW_CASES_RAW,
    CASES_CUMULATIVE,
    NEW_DEATHS_RAW,
    DEATHS_CUMULATIVE
FROM COVID_ANALYTICS.STAGING.COVID_COUNTRY_DAILY
WHERE COUNTRY = 'Latvia'
ORDER BY REPORT_DATE
LIMIT 50;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT LOCATION_KEY) AS LOCATION_COUNT,
    MIN(REPORT_DATE) AS FIRST_DATE,
    MAX(REPORT_DATE) AS LAST_DATE,
    COUNT_IF(HAS_NEGATIVE_CASE_CORRECTION) AS CASE_CORRECTIONS,
    COUNT_IF(HAS_NEGATIVE_DEATH_CORRECTION) AS DEATH_CORRECTIONS,
    SUM(SOURCE_ROW_COUNT - 1) AS DUPLICATE_SOURCE_ROWS_AGGREGATED
FROM COVID_ANALYTICS.STAGING.COVID_COUNTRY_DAILY;

SELECT
    COUNTRY,
    REPORT_DATE,
    NEW_CASES_RAW,
    NEW_DEATHS_RAW
FROM COVID_ANALYTICS.STAGING.COVID_COUNTRY_DAILY
WHERE NEW_CASES_RAW < 0
   OR NEW_DEATHS_RAW < 0
ORDER BY COUNTRY, REPORT_DATE;
