-- Build the version-selected WDI context independently of the frozen denominator.
-- The publisher creates and activates the permanent RAW tables before this file runs.

USE ROLE COVID_PROJECT_ADMIN;
USE WAREHOUSE COVID_WH;

CREATE OR REPLACE TRANSIENT TABLE COVID_ANALYTICS.MARTS.DIM_COUNTRY AS
SELECT
    covid.LOCATION_KEY,
    covid.COUNTRY,
    COALESCE(covid.COUNTRY_ISO2, legacy.COUNTRY_CODE_ISO2) AS ISO2,
    COALESCE(covid.COUNTRY_ISO3, legacy.COUNTRY_CODE_ISO3) AS ISO3,
    COALESCE(covid.COUNTRY_ISO3, legacy.COUNTRY_CODE_ISO3) IS NOT NULL
        AS IS_WORLD_BANK_CONTEXT_ELIGIBLE
FROM COVID_ANALYTICS.STAGING.COVID_COUNTRY_DAILY AS covid
LEFT JOIN COVID_ANALYTICS.RAW.WORLD_BANK_POPULATION_2020 AS legacy
    ON covid.COUNTRY_ISO2 = legacy.COUNTRY_CODE_ISO2
    OR covid.COUNTRY_ISO3 = legacy.COUNTRY_CODE_ISO3
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY covid.LOCATION_KEY
    ORDER BY covid.REPORT_DATE DESC, covid.COUNTRY
) = 1;

CREATE OR REPLACE VIEW
    COVID_ANALYTICS.STAGING.WORLD_BANK_COUNTRY_INDICATORS_CURRENT
AS
SELECT indicators.*
FROM COVID_ANALYTICS.RAW.WORLD_BANK_COUNTRY_INDICATORS AS indicators
INNER JOIN COVID_ANALYTICS.RAW.WORLD_BANK_INDICATOR_SNAPSHOTS AS snapshots
    ON indicators.SNAPSHOT_ID = snapshots.SNAPSHOT_ID
WHERE snapshots.IS_ACTIVE = TRUE
  AND snapshots.PUBLICATION_STATUS = 'ACTIVE';

CREATE OR REPLACE VIEW
    COVID_ANALYTICS.STAGING.WORLD_BANK_COUNTRY_INDICATORS_CLEAN
AS
SELECT
    SNAPSHOT_ID,
    CANONICAL_ISO2 AS ISO2,
    CANONICAL_ISO3 AS ISO3,
    COUNTRY_NAME,
    INDICATOR_CODE,
    INDICATOR_NAME,
    INDICATOR_UNIT,
    OBSERVATION_YEAR,
    INDICATOR_VALUE,
    IFF(INDICATOR_VALUE IS NULL, 'missing', 'available') AS VALUE_STATUS,
    SOURCE_LAST_UPDATED
FROM COVID_ANALYTICS.STAGING.WORLD_BANK_COUNTRY_INDICATORS_CURRENT
WHERE IDENTITY_MAPPING_STATUS IN ('matched_iso', 'matched_explicit_mapping')
  AND NOT IS_AGGREGATE
  AND OBSERVATION_YEAR BETWEEN 2019 AND 2021
  AND INDICATOR_CODE IN (
      'SP.POP.TOTL',
      'EN.POP.DNST',
      'SP.POP.65UP.TO.ZS',
      'NY.GDP.PCAP.KD',
      'SH.XPD.CHEX.PP.CD'
  )
  AND (
      (INDICATOR_CODE = 'SP.POP.TOTL'
       AND INDICATOR_NAME = 'Population, total'
       AND INDICATOR_UNIT = 'people')
      OR (INDICATOR_CODE = 'EN.POP.DNST'
          AND INDICATOR_NAME = 'Population density (people per sq. km of land area)'
          AND INDICATOR_UNIT = 'people per sq. km of land area')
      OR (INDICATOR_CODE = 'SP.POP.65UP.TO.ZS'
          AND INDICATOR_NAME = 'Population ages 65 and above (% of total population)'
          AND INDICATOR_UNIT = '% of total population')
      OR (INDICATOR_CODE = 'NY.GDP.PCAP.KD'
          AND INDICATOR_NAME = 'GDP per capita (constant 2015 US$)'
          AND INDICATOR_UNIT = 'constant 2015 US$')
      OR (INDICATOR_CODE = 'SH.XPD.CHEX.PP.CD'
          AND INDICATOR_NAME = 'Current health expenditure per capita, PPP (current international $)'
          AND INDICATOR_UNIT = 'current international $')
  );

CREATE TABLE IF NOT EXISTS COVID_ANALYTICS.MARTS.COUNTRY_COVID_DENOMINATOR (
    ISO2 VARCHAR,
    ISO3 VARCHAR NOT NULL,
    COUNTRY_NAME VARCHAR NOT NULL,
    COVID_RATE_POPULATION_2020 NUMBER(38, 0) NOT NULL,
    POPULATION_YEAR NUMBER(4, 0) NOT NULL,
    SOURCE_SNAPSHOT_ID VARCHAR NOT NULL,
    DENOMINATOR_VERSION VARCHAR NOT NULL,
    DENOMINATOR_POLICY VARCHAR NOT NULL,
    IS_FROZEN BOOLEAN NOT NULL,
    APPROVED_AT TIMESTAMP_TZ NOT NULL,
    CONSTRAINT PK_COUNTRY_COVID_DENOMINATOR PRIMARY KEY (ISO3) NOT ENFORCED
);

CREATE TABLE IF NOT EXISTS
    COVID_ANALYTICS.MARTS.COUNTRY_COVID_DENOMINATOR_HISTORY (
    ISO2 VARCHAR,
    ISO3 VARCHAR NOT NULL,
    COUNTRY_NAME VARCHAR NOT NULL,
    COVID_RATE_POPULATION_2020 NUMBER(38, 0) NOT NULL,
    POPULATION_YEAR NUMBER(4, 0) NOT NULL,
    SOURCE_SNAPSHOT_ID VARCHAR NOT NULL,
    DENOMINATOR_VERSION VARCHAR NOT NULL,
    DENOMINATOR_POLICY VARCHAR NOT NULL,
    IS_FROZEN BOOLEAN NOT NULL,
    APPROVED_AT TIMESTAMP_TZ NOT NULL,
    ARCHIVED_AT TIMESTAMP_TZ NOT NULL,
    CONSTRAINT PK_COUNTRY_COVID_DENOMINATOR_HISTORY
        PRIMARY KEY (DENOMINATOR_VERSION, ISO3) NOT ENFORCED
);

-- This insert is deliberately append-once. A WDI refresh must never silently
-- rewrite the population values that govern already-published per-capita rates.
INSERT INTO COVID_ANALYTICS.MARTS.COUNTRY_COVID_DENOMINATOR (
    ISO2,
    ISO3,
    COUNTRY_NAME,
    COVID_RATE_POPULATION_2020,
    POPULATION_YEAR,
    SOURCE_SNAPSHOT_ID,
    DENOMINATOR_VERSION,
    DENOMINATOR_POLICY,
    IS_FROZEN,
    APPROVED_AT
)
SELECT
    country.ISO2,
    country.ISO3,
    country.COUNTRY,
    legacy.POPULATION,
    legacy.POPULATION_YEAR,
    'legacy-world-bank-population-2020',
    'v1',
    'legacy_2020_population_preserved',
    TRUE,
    CURRENT_TIMESTAMP()
FROM COVID_ANALYTICS.MARTS.DIM_COUNTRY AS country
INNER JOIN COVID_ANALYTICS.RAW.WORLD_BANK_POPULATION_2020 AS legacy
    ON country.ISO3 = legacy.COUNTRY_CODE_ISO3
WHERE country.IS_WORLD_BANK_CONTEXT_ELIGIBLE
  AND NOT EXISTS (
      SELECT 1
      FROM COVID_ANALYTICS.MARTS.COUNTRY_COVID_DENOMINATOR AS existing
      WHERE existing.ISO3 = country.ISO3
  );

CREATE OR REPLACE TRANSIENT TABLE
    COVID_ANALYTICS.MARTS.COUNTRY_BASELINE_2019
AS
WITH PIVOTED AS (
    SELECT
        ISO3,
        MAX(IFF(INDICATOR_CODE = 'SP.POP.TOTL'
                AND OBSERVATION_YEAR = 2020, INDICATOR_VALUE, NULL))
            AS POPULATION_2020_CONTEXT,
        MAX(IFF(INDICATOR_CODE = 'EN.POP.DNST'
                AND OBSERVATION_YEAR = 2019, INDICATOR_VALUE, NULL))
            AS POPULATION_DENSITY_2019,
        MAX(IFF(INDICATOR_CODE = 'SP.POP.65UP.TO.ZS'
                AND OBSERVATION_YEAR = 2019, INDICATOR_VALUE, NULL))
            AS POPULATION_AGE_65_PLUS_PCT_2019,
        MAX(IFF(INDICATOR_CODE = 'NY.GDP.PCAP.KD'
                AND OBSERVATION_YEAR = 2019, INDICATOR_VALUE, NULL))
            AS REAL_GDP_PER_CAPITA_2019,
        MAX(IFF(INDICATOR_CODE = 'SH.XPD.CHEX.PP.CD'
                AND OBSERVATION_YEAR = 2019, INDICATOR_VALUE, NULL))
            AS HEALTH_EXPENDITURE_PER_CAPITA_PPP_2019,
        MAX(SNAPSHOT_ID) AS SNAPSHOT_ID
    FROM COVID_ANALYTICS.STAGING.WORLD_BANK_COUNTRY_INDICATORS_CLEAN
    GROUP BY ISO3
)
SELECT
    country.LOCATION_KEY,
    country.ISO2,
    country.ISO3,
    country.COUNTRY AS COUNTRY_NAME,
    indicators.POPULATION_2020_CONTEXT,
    indicators.POPULATION_DENSITY_2019,
    indicators.POPULATION_AGE_65_PLUS_PCT_2019,
    indicators.REAL_GDP_PER_CAPITA_2019,
    indicators.HEALTH_EXPENDITURE_PER_CAPITA_PPP_2019,
    IFF(indicators.POPULATION_2020_CONTEXT IS NULL, 'missing', 'available')
        AS POPULATION_2020_STATUS,
    IFF(indicators.POPULATION_DENSITY_2019 IS NULL, 'missing', 'available')
        AS POPULATION_DENSITY_2019_STATUS,
    IFF(indicators.POPULATION_AGE_65_PLUS_PCT_2019 IS NULL, 'missing', 'available')
        AS AGE_65_PLUS_2019_STATUS,
    IFF(indicators.REAL_GDP_PER_CAPITA_2019 IS NULL, 'missing', 'available')
        AS REAL_GDP_PER_CAPITA_2019_STATUS,
    IFF(indicators.HEALTH_EXPENDITURE_PER_CAPITA_PPP_2019 IS NULL,
        'missing', 'available') AS HEALTH_EXPENDITURE_PPP_2019_STATUS,
    (IFF(indicators.POPULATION_2020_CONTEXT IS NOT NULL, 1, 0)
     + IFF(indicators.POPULATION_DENSITY_2019 IS NOT NULL, 1, 0)
     + IFF(indicators.POPULATION_AGE_65_PLUS_PCT_2019 IS NOT NULL, 1, 0)
     + IFF(indicators.REAL_GDP_PER_CAPITA_2019 IS NOT NULL, 1, 0)
     + IFF(indicators.HEALTH_EXPENDITURE_PER_CAPITA_PPP_2019 IS NOT NULL, 1, 0))
        AS BASELINE_COMPLETENESS_COUNT,
    20 * (IFF(indicators.POPULATION_2020_CONTEXT IS NOT NULL, 1, 0)
     + IFF(indicators.POPULATION_DENSITY_2019 IS NOT NULL, 1, 0)
     + IFF(indicators.POPULATION_AGE_65_PLUS_PCT_2019 IS NOT NULL, 1, 0)
     + IFF(indicators.REAL_GDP_PER_CAPITA_2019 IS NOT NULL, 1, 0)
     + IFF(indicators.HEALTH_EXPENDITURE_PER_CAPITA_PPP_2019 IS NOT NULL, 1, 0))
        AS BASELINE_COMPLETENESS_PCT,
    indicators.SNAPSHOT_ID
FROM COVID_ANALYTICS.MARTS.DIM_COUNTRY AS country
LEFT JOIN PIVOTED AS indicators
    ON country.ISO3 = indicators.ISO3
WHERE country.IS_WORLD_BANK_CONTEXT_ELIGIBLE;

CREATE OR REPLACE TRANSIENT TABLE
    COVID_ANALYTICS.MARTS.COUNTRY_INDICATOR_ANNUAL
AS
SELECT
    country.ISO2,
    country.ISO3,
    country.COUNTRY AS COUNTRY_NAME,
    years.OBSERVATION_YEAR,
    MAX(IFF(data.INDICATOR_CODE = 'SP.POP.TOTL', data.INDICATOR_VALUE, NULL))
        AS POPULATION,
    MAX(IFF(data.INDICATOR_CODE = 'EN.POP.DNST', data.INDICATOR_VALUE, NULL))
        AS POPULATION_DENSITY,
    MAX(IFF(data.INDICATOR_CODE = 'SP.POP.65UP.TO.ZS', data.INDICATOR_VALUE, NULL))
        AS POPULATION_AGE_65_PLUS_PCT,
    MAX(IFF(data.INDICATOR_CODE = 'NY.GDP.PCAP.KD', data.INDICATOR_VALUE, NULL))
        AS REAL_GDP_PER_CAPITA,
    MAX(IFF(data.INDICATOR_CODE = 'SH.XPD.CHEX.PP.CD', data.INDICATOR_VALUE, NULL))
        AS HEALTH_EXPENDITURE_PER_CAPITA_PPP,
    MAX(data.SNAPSHOT_ID) AS SNAPSHOT_ID
FROM COVID_ANALYTICS.MARTS.DIM_COUNTRY AS country
CROSS JOIN (
    SELECT COLUMN1::NUMBER AS OBSERVATION_YEAR FROM VALUES (2019), (2020), (2021)
) AS years
LEFT JOIN COVID_ANALYTICS.STAGING.WORLD_BANK_COUNTRY_INDICATORS_CLEAN AS data
    ON country.ISO3 = data.ISO3
   AND years.OBSERVATION_YEAR = data.OBSERVATION_YEAR
WHERE country.IS_WORLD_BANK_CONTEXT_ELIGIBLE
GROUP BY country.ISO2, country.ISO3, country.COUNTRY, years.OBSERVATION_YEAR;

SELECT
    (SELECT COUNT(*) FROM COVID_ANALYTICS.RAW.WORLD_BANK_INDICATOR_SNAPSHOTS
     WHERE IS_ACTIVE) AS ACTIVE_SNAPSHOT_COUNT,
    (SELECT COUNT(*) FROM COVID_ANALYTICS.MARTS.COUNTRY_BASELINE_2019)
        AS BASELINE_ROWS,
    (SELECT COUNT(*) FROM COVID_ANALYTICS.MARTS.COUNTRY_COVID_DENOMINATOR)
        AS FROZEN_DENOMINATOR_ROWS;
