-- Run this file after: uv run python scripts/load_population.py
-- Run each statement separately in a Snowsight SQL worksheet.

USE ROLE COVID_PROJECT_ADMIN;

USE WAREHOUSE COVID_WH;

-- The current World Bank snapshot should contain 217 rows.
SELECT
    COUNT(*) AS ROW_COUNT
FROM COVID_ANALYTICS.RAW.WORLD_BANK_POPULATION_2020;

SELECT *
FROM COVID_ANALYTICS.RAW.WORLD_BANK_POPULATION_2020
ORDER BY COUNTRY_NAME
LIMIT 20;

SELECT
    COUNT(*) AS TOTAL_COUNTRIES,
    COUNT_IF(POPULATION IS NULL) AS MISSING_POPULATION,
    MIN(POPULATION) AS MIN_POPULATION,
    MAX(POPULATION) AS MAX_POPULATION
FROM COVID_ANALYTICS.RAW.WORLD_BANK_POPULATION_2020;

-- This query should return no rows.
SELECT
    COUNTRY_CODE_ISO2,
    COUNT(*) AS RECORD_COUNT
FROM COVID_ANALYTICS.RAW.WORLD_BANK_POPULATION_2020
GROUP BY COUNTRY_CODE_ISO2
HAVING COUNT(*) > 1;
