-- Run after the staging view and population table exist.
-- Run each statement separately in a Snowsight SQL worksheet.

USE ROLE COVID_PROJECT_ADMIN;

USE WAREHOUSE COVID_WH;

CREATE OR REPLACE VIEW
    COVID_ANALYTICS.MARTS.COVID_ENRICHED
AS
SELECT
    covid.COUNTRY,
    COALESCE(
        covid.COUNTRY_ISO2,
        population.COUNTRY_CODE_ISO2
    ) AS COUNTRY_ISO2,
    COALESCE(
        covid.COUNTRY_ISO3,
        population.COUNTRY_CODE_ISO3
    ) AS COUNTRY_ISO3,
    covid.LOCATION_KEY,
    covid.REPORT_DATE,
    covid.NEW_CASES_RAW,
    covid.NEW_DEATHS_RAW,
    covid.CASES_CUMULATIVE,
    covid.DEATHS_CUMULATIVE,
    population.COUNTRY_NAME AS POPULATION_COUNTRY_NAME,
    population.POPULATION,
    population.POPULATION_YEAR,
    ROUND(
        covid.NEW_CASES_RAW
        / NULLIF(population.POPULATION, 0) * 100000,
        2
    ) AS NEW_CASES_PER_100K,
    ROUND(
        covid.NEW_DEATHS_RAW
        / NULLIF(population.POPULATION, 0) * 100000,
        2
    ) AS NEW_DEATHS_PER_100K,
    ROUND(
        covid.CASES_CUMULATIVE
        / NULLIF(population.POPULATION, 0) * 100000,
        2
    ) AS CASES_PER_100K,
    ROUND(
        covid.DEATHS_CUMULATIVE
        / NULLIF(population.POPULATION, 0) * 100000,
        2
    ) AS DEATHS_PER_100K,
    ROUND(
        covid.DEATHS_CUMULATIVE
        / NULLIF(covid.CASES_CUMULATIVE, 0) * 100,
        4
    ) AS MORTALITY_RATE_PERCENT,
    CASE
        WHEN population.POPULATION IS NOT NULL THEN 'MATCHED'
        WHEN NOT covid.EXPECTED_POPULATION_MATCH THEN 'SOURCE_UNAVAILABLE'
        WHEN covid.COUNTRY_ISO2 IS NULL
         AND covid.COUNTRY_ISO3 IS NULL THEN 'NO_ISO_CODE'
        ELSE 'UNMATCHED'
    END AS POPULATION_JOIN_STATUS,
    covid.HAS_NEGATIVE_CASE_CORRECTION,
    covid.HAS_NEGATIVE_DEATH_CORRECTION,
    covid.MAPPING_APPLIED,
    covid.SOURCE_ROW_COUNT
FROM COVID_ANALYTICS.STAGING.COVID_COUNTRY_DAILY AS covid
LEFT JOIN COVID_ANALYTICS.RAW.WORLD_BANK_POPULATION_2020 AS population
    ON covid.COUNTRY_ISO2 = population.COUNTRY_CODE_ISO2
    OR covid.COUNTRY_ISO3 = population.COUNTRY_CODE_ISO3;

SELECT
    COUNTRY,
    REPORT_DATE,
    NEW_CASES_RAW,
    CASES_CUMULATIVE,
    NEW_CASES_PER_100K,
    CASES_PER_100K,
    NEW_DEATHS_RAW,
    DEATHS_CUMULATIVE,
    DEATHS_PER_100K,
    MORTALITY_RATE_PERCENT
FROM COVID_ANALYTICS.MARTS.COVID_ENRICHED
WHERE COUNTRY = 'Latvia'
ORDER BY REPORT_DATE
LIMIT 50;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT LOCATION_KEY) AS LOCATION_COUNT,
    MIN(REPORT_DATE) AS FIRST_DATE,
    MAX(REPORT_DATE) AS LAST_DATE,
    COUNT_IF(POPULATION IS NULL) AS ROWS_WITHOUT_POPULATION
FROM COVID_ANALYTICS.MARTS.COVID_ENRICHED;

-- SOURCE_UNAVAILABLE rows are expected; investigate UNMATCHED and NO_ISO_CODE.
SELECT
    POPULATION_JOIN_STATUS,
    COUNT(DISTINCT LOCATION_KEY) AS LOCATION_COUNT,
    COUNT(*) AS ROW_COUNT
FROM COVID_ANALYTICS.MARTS.COVID_ENRICHED
GROUP BY POPULATION_JOIN_STATUS
ORDER BY POPULATION_JOIN_STATUS;

SELECT DISTINCT
    COUNTRY,
    COUNTRY_ISO2,
    COUNTRY_ISO3,
    POPULATION_JOIN_STATUS
FROM COVID_ANALYTICS.MARTS.COVID_ENRICHED
WHERE POPULATION IS NULL
ORDER BY POPULATION_JOIN_STATUS, COUNTRY;
