-- Rebuild reproducible reporting objects after the active snapshot and denominator
-- have been selected. CREATE OR REPLACE also migrates the pre-release column contract.

USE ROLE COVID_PROJECT_ADMIN;
USE WAREHOUSE COVID_WH;

CREATE OR REPLACE TRANSIENT TABLE
    COVID_ANALYTICS.MARTS.COUNTRY_LATEST_METRICS
AS
SELECT
    LOCATION_KEY,
    COUNTRY,
    COUNTRY_ISO2,
    COUNTRY_ISO3,
    REPORT_DATE,
    COVID_RATE_POPULATION_2020,
    COVID_RATE_POPULATION_YEAR,
    DENOMINATOR_SOURCE_SNAPSHOT_ID,
    DENOMINATOR_VERSION,
    DENOMINATOR_POLICY,
    DENOMINATOR_IS_FROZEN,
    CASES_CUMULATIVE,
    DEATHS_CUMULATIVE,
    CASES_PER_100K,
    DEATHS_PER_100K,
    MORTALITY_RATE_PERCENT,
    DENOMINATOR_JOIN_STATUS
FROM COVID_ANALYTICS.MARTS.COVID_ENRICHED
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY LOCATION_KEY
    ORDER BY REPORT_DATE DESC
) = 1;

CREATE OR REPLACE VIEW COVID_ANALYTICS.MARTS.COUNTRY_CONTEXT_ANALYSIS AS
WITH GDP AS (
    SELECT
        ISO3,
        MAX(IFF(OBSERVATION_YEAR = 2019, REAL_GDP_PER_CAPITA, NULL)) AS GDP_2019,
        MAX(IFF(OBSERVATION_YEAR = 2020, REAL_GDP_PER_CAPITA, NULL)) AS GDP_2020,
        MAX(IFF(OBSERVATION_YEAR = 2021, REAL_GDP_PER_CAPITA, NULL)) AS GDP_2021,
        MAX(SNAPSHOT_ID) AS SNAPSHOT_ID
    FROM COVID_ANALYTICS.MARTS.COUNTRY_INDICATOR_ANNUAL
    GROUP BY ISO3
)
SELECT
    baseline.*,
    latest.COVID_RATE_POPULATION_2020,
    latest.COVID_RATE_POPULATION_YEAR,
    latest.DENOMINATOR_SOURCE_SNAPSHOT_ID,
    latest.DENOMINATOR_VERSION,
    latest.DENOMINATOR_POLICY,
    latest.DENOMINATOR_IS_FROZEN,
    latest.REPORT_DATE AS COVID_LATEST_REPORT_DATE,
    latest.CASES_CUMULATIVE,
    latest.DEATHS_CUMULATIVE,
    latest.CASES_PER_100K,
    latest.DEATHS_PER_100K,
    latest.MORTALITY_RATE_PERCENT,
    GDP.GDP_2019 AS REAL_GDP_PER_CAPITA_2019_ANNUAL,
    GDP.GDP_2020 AS REAL_GDP_PER_CAPITA_2020,
    GDP.GDP_2021 AS REAL_GDP_PER_CAPITA_2021,
    100 * (GDP.GDP_2020 / NULLIF(GDP.GDP_2019, 0) - 1)
        AS REAL_GDP_PER_CAPITA_CHANGE_2020_VS_2019_PCT,
    100 * (GDP.GDP_2021 / NULLIF(GDP.GDP_2019, 0) - 1)
        AS REAL_GDP_PER_CAPITA_CHANGE_2021_VS_2019_PCT,
    100 * (GDP.GDP_2021 / NULLIF(GDP.GDP_2020, 0) - 1)
        AS REAL_GDP_PER_CAPITA_CHANGE_2021_VS_2020_PCT,
    IFF(GDP.GDP_2019 IS NULL OR GDP.GDP_2020 IS NULL,
        'missing_input', IFF(GDP.GDP_2019 = 0, 'zero_denominator', 'available'))
        AS REAL_GDP_PER_CAPITA_CHANGE_2020_VS_2019_STATUS,
    IFF(GDP.GDP_2019 IS NULL OR GDP.GDP_2021 IS NULL,
        'missing_input', IFF(GDP.GDP_2019 = 0, 'zero_denominator', 'available'))
        AS REAL_GDP_PER_CAPITA_CHANGE_2021_VS_2019_STATUS,
    IFF(GDP.GDP_2020 IS NULL OR GDP.GDP_2021 IS NULL,
        'missing_input', IFF(GDP.GDP_2020 = 0, 'zero_denominator', 'available'))
        AS REAL_GDP_PER_CAPITA_CHANGE_2021_VS_2020_STATUS
FROM COVID_ANALYTICS.MARTS.COUNTRY_BASELINE_2019 AS baseline
LEFT JOIN GDP ON baseline.ISO3 = GDP.ISO3
LEFT JOIN COVID_ANALYTICS.MARTS.COUNTRY_LATEST_METRICS AS latest
    ON baseline.ISO3 = latest.COUNTRY_ISO3;

CREATE OR REPLACE VIEW COVID_ANALYTICS.MARTS.CASE_INCREASE_PATTERNS AS
SELECT *
FROM COVID_ANALYTICS.STAGING.COVID_COUNTRY_DAILY
MATCH_RECOGNIZE (
    PARTITION BY LOCATION_KEY, COUNTRY, COUNTRY_ISO2, COUNTRY_ISO3
    ORDER BY REPORT_DATE
    MEASURES
        MATCH_NUMBER() AS MATCH_NUMBER,
        FIRST(REPORT_DATE) AS START_DATE,
        LAST(REPORT_DATE) AS END_DATE,
        COUNT(*) AS DAYS_IN_PATTERN,
        COUNT(INCREASE_DAY.*) AS CONSECUTIVE_INCREASES,
        FIRST(NEW_CASES_RAW) AS START_CASES,
        LAST(NEW_CASES_RAW) AS END_CASES
    ONE ROW PER MATCH
    AFTER MATCH SKIP PAST LAST ROW
    PATTERN (START_DAY INCREASE_DAY{3,})
    DEFINE
        START_DAY AS TRUE,
        INCREASE_DAY AS NEW_CASES_RAW > LAG(NEW_CASES_RAW)
            AND DATEDIFF('DAY', LAG(REPORT_DATE), REPORT_DATE) = 1
);

SELECT COUNT(*) AS LATEST_COUNTRY_ROWS
FROM COVID_ANALYTICS.MARTS.COUNTRY_LATEST_METRICS;

SELECT COUNT(*) AS COUNTRY_CONTEXT_ROWS
FROM COVID_ANALYTICS.MARTS.COUNTRY_CONTEXT_ANALYSIS;
