-- Re-run this file after refreshing upstream data. The transient table is a
-- deliberately small, precomputed latest-country snapshot for API/reporting.
-- Run each statement separately in a Snowsight SQL worksheet.

USE ROLE COVID_PROJECT_ADMIN;

USE WAREHOUSE COVID_WH;

CREATE OR REPLACE TRANSIENT TABLE
    COVID_ANALYTICS.MARTS.COUNTRY_LATEST_METRICS
AS
SELECT
    LOCATION_KEY,
    COUNTRY,
    COUNTRY_ISO2,
    COUNTRY_ISO3,
    REPORT_DATE,
    POPULATION,
    CASES_CUMULATIVE,
    DEATHS_CUMULATIVE,
    CASES_PER_100K,
    DEATHS_PER_100K,
    MORTALITY_RATE_PERCENT,
    POPULATION_JOIN_STATUS
FROM COVID_ANALYTICS.MARTS.COVID_ENRICHED
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY LOCATION_KEY
    ORDER BY REPORT_DATE DESC
) = 1;

CREATE OR REPLACE VIEW
    COVID_ANALYTICS.MARTS.CASE_INCREASE_PATTERNS
AS
SELECT *
FROM COVID_ANALYTICS.STAGING.COVID_COUNTRY_DAILY
MATCH_RECOGNIZE (
    PARTITION BY
        LOCATION_KEY,
        COUNTRY,
        COUNTRY_ISO2,
        COUNTRY_ISO3
    ORDER BY REPORT_DATE
    MEASURES
        MATCH_NUMBER() AS MATCH_NUMBER,
        FIRST(REPORT_DATE) AS START_DATE,
        LAST(REPORT_DATE) AS END_DATE,
        COUNT(*) AS DAYS_IN_PATTERN,
        COUNT(INCREASE_DAY.*) AS CONSECUTIVE_INCREASES,
        FIRST(NEW_CASES_RAW) AS START_CASES,
        LAST(NEW_CASES_RAW) AS END_CASES
    ONE ROW PER MATCH
    AFTER MATCH SKIP PAST LAST ROW
    PATTERN (START_DAY INCREASE_DAY{3,})
    DEFINE
        START_DAY AS TRUE,
        INCREASE_DAY AS
            NEW_CASES_RAW > LAG(NEW_CASES_RAW)
            AND DATEDIFF(
                'DAY',
                LAG(REPORT_DATE),
                REPORT_DATE
            ) = 1
);

SELECT COUNT(*) AS LATEST_COUNTRY_ROWS
FROM COVID_ANALYTICS.MARTS.COUNTRY_LATEST_METRICS;

SELECT COUNT(*) AS CASE_INCREASE_PATTERN_ROWS
FROM COVID_ANALYTICS.MARTS.CASE_INCREASE_PATTERNS;
