-- Run each statement separately in a Snowsight SQL worksheet.

USE ROLE COVID_PROJECT_ADMIN;

USE WAREHOUSE COVID_WH;

-- Latest record for every country/location.
SELECT *
FROM COVID_ANALYTICS.MARTS.COUNTRY_LATEST_METRICS
ORDER BY COUNTRY;

-- Top countries by cumulative cases per 100,000 people.
SELECT
    COUNTRY,
    POPULATION,
    CASES_CUMULATIVE,
    CASES_PER_100K
FROM COVID_ANALYTICS.MARTS.COUNTRY_LATEST_METRICS
WHERE POPULATION IS NOT NULL
ORDER BY CASES_PER_100K DESC
LIMIT 20;

-- Top countries by cumulative deaths per 100,000 people.
SELECT
    COUNTRY,
    POPULATION,
    DEATHS_CUMULATIVE,
    DEATHS_PER_100K
FROM COVID_ANALYTICS.MARTS.COUNTRY_LATEST_METRICS
WHERE POPULATION IS NOT NULL
ORDER BY DEATHS_PER_100K DESC
LIMIT 20;

-- The case threshold avoids rankings dominated by tiny denominators.
SELECT
    COUNTRY,
    CASES_CUMULATIVE,
    DEATHS_CUMULATIVE,
    MORTALITY_RATE_PERCENT
FROM COVID_ANALYTICS.MARTS.COUNTRY_LATEST_METRICS
WHERE CASES_CUMULATIVE >= 10000
ORDER BY MORTALITY_RATE_PERCENT DESC
LIMIT 20;

-- Compare the Baltic countries.
SELECT
    COUNTRY,
    POPULATION,
    CASES_CUMULATIVE,
    DEATHS_CUMULATIVE,
    CASES_PER_100K,
    DEATHS_PER_100K,
    MORTALITY_RATE_PERCENT
FROM COVID_ANALYTICS.MARTS.COUNTRY_LATEST_METRICS
WHERE COUNTRY IN ('Latvia', 'Estonia', 'Lithuania')
ORDER BY COUNTRY;

-- Longest detected runs of daily case increases.
SELECT
    COUNTRY,
    START_DATE,
    END_DATE,
    DAYS_IN_PATTERN,
    CONSECUTIVE_INCREASES,
    START_CASES,
    END_CASES
FROM COVID_ANALYTICS.MARTS.CASE_INCREASE_PATTERNS
ORDER BY CONSECUTIVE_INCREASES DESC, END_CASES DESC
LIMIT 50;
