-- Manual post-cutover migration. Run only after every consumer reads the frozen
-- denominator object and one release has passed reconciliation.

USE ROLE COVID_PROJECT_ADMIN;
USE WAREHOUSE COVID_WH;

ALTER TABLE IF EXISTS COVID_ANALYTICS.RAW.WORLD_BANK_POPULATION_2020
    RENAME TO COVID_ANALYTICS.RAW.WORLD_BANK_POPULATION_2020_LEGACY;

CREATE OR REPLACE VIEW COVID_ANALYTICS.RAW.WORLD_BANK_POPULATION_2020 AS
SELECT
    ISO2 AS COUNTRY_CODE_ISO2,
    ISO3 AS COUNTRY_CODE_ISO3,
    COUNTRY_NAME,
    COVID_RATE_POPULATION_2020 AS POPULATION,
    POPULATION_YEAR
FROM COVID_ANALYTICS.MARTS.COUNTRY_COVID_DENOMINATOR;
