-- Build a parallel ECDC/JHU series without changing the API-facing marts.
-- Run after 06_create_reporting_objects.sql so the active World Bank snapshot
-- and the approved frozen COVID denominator are available.

USE ROLE COVID_PROJECT_ADMIN;
USE WAREHOUSE COVID_WH;

CREATE TABLE IF NOT EXISTS COVID_ANALYTICS.RAW.JHU_GEOGRAPHY_POLICY (
    SOURCE_COUNTRY_NAME VARCHAR NOT NULL,
    SOURCE_ISO2 VARCHAR,
    CANONICAL_ISO2 VARCHAR,
    CANONICAL_ISO3 VARCHAR,
    SELECTED_LOCATION_LEVEL VARCHAR NOT NULL,
    MAPPING_STATUS VARCHAR NOT NULL,
    SELECTION_REASON VARCHAR NOT NULL,
    IS_INCLUDED BOOLEAN NOT NULL,
    JHU_START_DATE DATE,
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

-- Existing exploratory accounts may have the policy table without this column.
ALTER TABLE COVID_ANALYTICS.RAW.JHU_GEOGRAPHY_POLICY
    ADD COLUMN IF NOT EXISTS JHU_START_DATE DATE;

MERGE INTO COVID_ANALYTICS.RAW.JHU_GEOGRAPHY_POLICY AS target
USING (
    SELECT
        column1::VARCHAR AS SOURCE_COUNTRY_NAME,
        column2::VARCHAR AS SOURCE_ISO2,
        column3::VARCHAR AS CANONICAL_ISO2,
        column4::VARCHAR AS CANONICAL_ISO3,
        column5::VARCHAR AS SELECTED_LOCATION_LEVEL,
        column6::VARCHAR AS MAPPING_STATUS,
        column7::VARCHAR AS SELECTION_REASON,
        column8::BOOLEAN AS IS_INCLUDED,
        column9::DATE AS JHU_START_DATE
    FROM VALUES
        (
            'Antarctica', 'AQ', 'AQ', 'ATA', 'COUNTRY',
            'EXCLUDED_ANALYTICAL_SCOPE',
            'Valid ISO identity, but excluded from the resident-country analytical mart',
            FALSE, NULL
        ),
        (
            'Australia', 'AU', 'AU', 'AUS', 'PROVINCE', 'MAPPED',
            'No national row; aggregate eight province rows', TRUE, NULL
        ),
        (
            'Canada', 'CA', 'CA', 'CAN', 'PROVINCE', 'MAPPED',
            'National rows contain NULL values; aggregate sixteen province rows',
            TRUE, NULL
        ),
        (
            'China', 'CN', 'CN', 'CHN', 'PROVINCE', 'MAPPED',
            'No national row; aggregate thirty-four province rows', TRUE, NULL
        ),
        (
            'Cruise Ship', NULL, NULL, NULL, 'EXCLUDED',
            'EXCLUDED_NON_COUNTRY', 'Aggregate cruise-ship entity', FALSE, NULL
        ),
        (
            'Denmark', 'DK', 'DK', 'DNK', 'COUNTRY', 'MAPPED',
            'Use national row; province rows are not a complete partition',
            TRUE, NULL
        ),
        (
            'France', 'FR', 'FR', 'FRA', 'COUNTRY', 'MAPPED',
            'Use national row; province rows are not a complete partition',
            TRUE, NULL
        ),
        (
            'Holy See (Vatican City State)', 'VA', 'VA', 'VAT', 'COUNTRY',
            'EXPLICIT_MAPPING',
            'Valid ISO identity absent from the World Bank mapping source',
            TRUE, NULL
        ),
        (
            'Korea, North', NULL, 'KP', 'PRK', 'COUNTRY',
            'EXPLICIT_MAPPING', 'JHU ISO2 is missing; explicit canonical mapping',
            TRUE, NULL
        ),
        (
            'Kosovo', NULL, 'XK', 'XKX', 'COUNTRY',
            'EXPLICIT_PROJECT_MAPPING', 'Project-specific country-code convention',
            TRUE, NULL
        ),
        (
            'MS Zaandam', NULL, NULL, NULL, 'EXCLUDED',
            'EXCLUDED_NON_COUNTRY', 'Cruise-ship record', FALSE, NULL
        ),
        (
            'Micronesia', NULL, 'FM', 'FSM', 'COUNTRY',
            'EXPLICIT_MAPPING', 'JHU ISO2 is missing; explicit canonical mapping',
            TRUE, NULL
        ),
        (
            'Namibia', NULL, 'NA', 'NAM', 'COUNTRY',
            'EXPLICIT_MAPPING', 'JHU ISO2 is missing; explicit canonical mapping',
            TRUE, NULL
        ),
        (
            'Netherlands', 'NL', 'NL', 'NLD', 'COUNTRY', 'MAPPED',
            'Use national row; province rows are not a complete partition',
            TRUE, NULL
        ),
        (
            'New Zealand', 'NZ', 'NZ', 'NZL', 'COUNTRY', 'MAPPED',
            'Use national row; province rows are not a complete partition',
            TRUE, NULL
        ),
        (
            'Spain', 'ES', 'ES', 'ESP', 'COUNTRY', 'MAPPED',
            'ECDC series ends 2020-12-13; JHU cutover shifted one day earlier to avoid gap',
            TRUE, DATE '2020-12-14'
        ),
        (
            'Summer Olympics 2020', NULL, NULL, NULL, 'EXCLUDED',
            'EXCLUDED_NON_COUNTRY', 'Event record rather than a country',
            FALSE, NULL
        ),
        (
            'Syria', NULL, 'SY', 'SYR', 'COUNTRY',
            'EXPLICIT_MAPPING', 'JHU ISO2 is missing; explicit canonical mapping',
            TRUE, NULL
        ),
        (
            'Taiwan, Province of China', 'TW', 'TW', 'TWN', 'COUNTRY',
            'EXPLICIT_MAPPING',
            'Valid ISO identity absent from the World Bank mapping source',
            TRUE, NULL
        ),
        (
            'United Kingdom', 'GB', 'GB', 'GBR', 'COUNTRY', 'MAPPED',
            'Use national row; province rows are not a complete partition',
            TRUE, NULL
        ),
        (
            'United States', 'US', 'US', 'USA', 'COUNTY', 'MAPPED',
            'No national row; aggregate county-level records', TRUE, NULL
        ),
        (
            'Winter Olympics 2022', NULL, NULL, NULL, 'EXCLUDED',
            'EXCLUDED_NON_COUNTRY', 'Event record rather than a country',
            FALSE, NULL
        )
) AS source
ON UPPER(target.SOURCE_COUNTRY_NAME) = UPPER(source.SOURCE_COUNTRY_NAME)
WHEN MATCHED THEN UPDATE SET
    target.SOURCE_ISO2 = source.SOURCE_ISO2,
    target.CANONICAL_ISO2 = source.CANONICAL_ISO2,
    target.CANONICAL_ISO3 = source.CANONICAL_ISO3,
    target.SELECTED_LOCATION_LEVEL = source.SELECTED_LOCATION_LEVEL,
    target.MAPPING_STATUS = source.MAPPING_STATUS,
    target.SELECTION_REASON = source.SELECTION_REASON,
    target.IS_INCLUDED = source.IS_INCLUDED,
    target.JHU_START_DATE = source.JHU_START_DATE,
    target.UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    SOURCE_COUNTRY_NAME,
    SOURCE_ISO2,
    CANONICAL_ISO2,
    CANONICAL_ISO3,
    SELECTED_LOCATION_LEVEL,
    MAPPING_STATUS,
    SELECTION_REASON,
    IS_INCLUDED,
    JHU_START_DATE
)
VALUES (
    source.SOURCE_COUNTRY_NAME,
    source.SOURCE_ISO2,
    source.CANONICAL_ISO2,
    source.CANONICAL_ISO3,
    source.SELECTED_LOCATION_LEVEL,
    source.MAPPING_STATUS,
    source.SELECTION_REASON,
    source.IS_INCLUDED,
    source.JHU_START_DATE
);

CREATE OR REPLACE VIEW
    COVID_ANALYTICS.STAGING.CANONICAL_COUNTRY_CODE_MAP
AS
SELECT
    UPPER(TRIM(indicators.CANONICAL_ISO2)) AS COUNTRY_ISO2,
    UPPER(TRIM(indicators.CANONICAL_ISO3)) AS COUNTRY_ISO3,
    MIN(TRIM(indicators.COUNTRY_NAME)) AS COUNTRY_NAME
FROM COVID_ANALYTICS.RAW.WORLD_BANK_COUNTRY_INDICATORS AS indicators
INNER JOIN COVID_ANALYTICS.RAW.WORLD_BANK_INDICATOR_SNAPSHOTS AS snapshots
    ON indicators.SNAPSHOT_ID = snapshots.SNAPSHOT_ID
WHERE snapshots.IS_ACTIVE
  AND snapshots.PUBLICATION_STATUS = 'ACTIVE'
  AND NULLIF(TRIM(indicators.CANONICAL_ISO2), '') IS NOT NULL
  AND NULLIF(TRIM(indicators.CANONICAL_ISO3), '') IS NOT NULL
  AND NOT indicators.IS_AGGREGATE
GROUP BY
    UPPER(TRIM(indicators.CANONICAL_ISO2)),
    UPPER(TRIM(indicators.CANONICAL_ISO3));

CREATE OR REPLACE TRANSIENT TABLE
    COVID_ANALYTICS.STAGING.JHU_COUNTRY_CUMULATIVE
AS
WITH IDENTIFIED_SOURCE AS (
    SELECT
        TRIM(source.COUNTRY_REGION) AS SOURCE_COUNTRY_NAME,
        NULLIF(UPPER(TRIM(source.ISO3166_1)), '') AS SOURCE_ISO2,
        COALESCE(
            policy.CANONICAL_ISO2,
            source_map.COUNTRY_ISO2
        ) AS CANONICAL_ISO2,
        COALESCE(
            policy.CANONICAL_ISO3,
            source_map.COUNTRY_ISO3
        ) AS CANONICAL_ISO3,
        COALESCE(
            policy_map.COUNTRY_NAME,
            source_map.COUNTRY_NAME,
            policy.SOURCE_COUNTRY_NAME,
            REPLACE(TRIM(source.COUNTRY_REGION), '_', ' ')
        ) AS COUNTRY_NAME,
        source.DATE::DATE AS REPORT_DATE,
        LOWER(TRIM(source.CASE_TYPE)) AS CASE_TYPE,
        source.CASES,
        source.PROVINCE_STATE,
        source.COUNTY,
        COALESCE(policy.SELECTED_LOCATION_LEVEL, 'COUNTRY')
            AS SELECTED_LOCATION_LEVEL,
        COALESCE(
            policy.MAPPING_STATUS,
            IFF(source_map.COUNTRY_ISO3 IS NULL, 'UNMAPPED', 'MAPPED')
        ) AS MAPPING_STATUS,
        COALESCE(
            policy.IS_INCLUDED,
            source_map.COUNTRY_ISO3 IS NOT NULL
        ) AS IS_INCLUDED
    FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.JHU_COVID_19_TIMESERIES AS source
    LEFT JOIN COVID_ANALYTICS.RAW.JHU_GEOGRAPHY_POLICY AS policy
        ON UPPER(TRIM(source.COUNTRY_REGION))
            = UPPER(policy.SOURCE_COUNTRY_NAME)
       AND EQUAL_NULL(
            NULLIF(UPPER(TRIM(source.ISO3166_1)), ''),
            policy.SOURCE_ISO2
       )
    LEFT JOIN COVID_ANALYTICS.STAGING.CANONICAL_COUNTRY_CODE_MAP AS source_map
        ON NULLIF(UPPER(TRIM(source.ISO3166_1)), '')
            = source_map.COUNTRY_ISO2
    LEFT JOIN COVID_ANALYTICS.STAGING.CANONICAL_COUNTRY_CODE_MAP AS policy_map
        ON policy.CANONICAL_ISO2 = policy_map.COUNTRY_ISO2
    WHERE source.COUNTRY_REGION IS NOT NULL
      AND source.DATE IS NOT NULL
      AND LOWER(TRIM(source.CASE_TYPE)) IN ('confirmed', 'deaths')
),
SELECTED_GEOGRAPHY AS (
    SELECT *
    FROM IDENTIFIED_SOURCE
    WHERE IS_INCLUDED
      AND CANONICAL_ISO3 IS NOT NULL
      AND (
          (
              SELECTED_LOCATION_LEVEL = 'COUNTRY'
              AND NULLIF(TRIM(PROVINCE_STATE), '') IS NULL
              AND NULLIF(TRIM(COUNTY), '') IS NULL
          )
          OR (
              SELECTED_LOCATION_LEVEL = 'PROVINCE'
              AND NULLIF(TRIM(PROVINCE_STATE), '') IS NOT NULL
              AND NULLIF(TRIM(COUNTY), '') IS NULL
          )
          OR (
              SELECTED_LOCATION_LEVEL = 'COUNTY'
              AND NULLIF(TRIM(COUNTY), '') IS NOT NULL
          )
      )
),
AGGREGATED AS (
    SELECT
        SOURCE_COUNTRY_NAME,
        SOURCE_ISO2,
        CANONICAL_ISO2,
        CANONICAL_ISO3,
        COUNTRY_NAME,
        REPORT_DATE,
        SELECTED_LOCATION_LEVEL,
        MAPPING_STATUS,
        CASE_TYPE,
        SUM(CASES)::NUMBER(38, 0) AS SOURCE_CUMULATIVE_VALUE,
        COUNT(*) AS SOURCE_ROW_COUNT,
        COUNT(CASES) AS NON_NULL_SOURCE_ROWS,
        COUNT_IF(CASES != TRUNC(CASES)) AS FRACTIONAL_SOURCE_ROWS
    FROM SELECTED_GEOGRAPHY
    GROUP BY
        SOURCE_COUNTRY_NAME,
        SOURCE_ISO2,
        CANONICAL_ISO2,
        CANONICAL_ISO3,
        COUNTRY_NAME,
        REPORT_DATE,
        SELECTED_LOCATION_LEVEL,
        MAPPING_STATUS,
        CASE_TYPE
),
PIVOTED AS (
    SELECT
        SOURCE_COUNTRY_NAME,
        SOURCE_ISO2,
        CANONICAL_ISO2,
        CANONICAL_ISO3,
        COUNTRY_NAME,
        REPORT_DATE,
        SELECTED_LOCATION_LEVEL,
        MAPPING_STATUS,
        MAX(IFF(CASE_TYPE = 'confirmed', SOURCE_CUMULATIVE_VALUE, NULL))
            AS SOURCE_CUMULATIVE_CASES,
        MAX(IFF(CASE_TYPE = 'deaths', SOURCE_CUMULATIVE_VALUE, NULL))
            AS SOURCE_CUMULATIVE_DEATHS,
        MAX(IFF(CASE_TYPE = 'confirmed', SOURCE_ROW_COUNT, NULL))
            AS CASES_SOURCE_ROW_COUNT,
        MAX(IFF(CASE_TYPE = 'confirmed', NON_NULL_SOURCE_ROWS, NULL))
            AS CASES_NON_NULL_SOURCE_ROWS,
        MAX(IFF(CASE_TYPE = 'deaths', SOURCE_ROW_COUNT, NULL))
            AS DEATHS_SOURCE_ROW_COUNT,
        MAX(IFF(CASE_TYPE = 'deaths', NON_NULL_SOURCE_ROWS, NULL))
            AS DEATHS_NON_NULL_SOURCE_ROWS,
        MAX(IFF(CASE_TYPE = 'confirmed', FRACTIONAL_SOURCE_ROWS, NULL))
            AS FRACTIONAL_CASE_SOURCE_ROWS,
        MAX(IFF(CASE_TYPE = 'deaths', FRACTIONAL_SOURCE_ROWS, NULL))
            AS FRACTIONAL_DEATH_SOURCE_ROWS
    FROM AGGREGATED
    GROUP BY
        SOURCE_COUNTRY_NAME,
        SOURCE_ISO2,
        CANONICAL_ISO2,
        CANONICAL_ISO3,
        COUNTRY_NAME,
        REPORT_DATE,
        SELECTED_LOCATION_LEVEL,
        MAPPING_STATUS
)
SELECT *
FROM PIVOTED
WHERE SOURCE_CUMULATIVE_CASES IS NOT NULL
  AND SOURCE_CUMULATIVE_DEATHS IS NOT NULL;

CREATE OR REPLACE TRANSIENT TABLE
    COVID_ANALYTICS.STAGING.JHU_COUNTRY_DAILY
AS
WITH LAGGED AS (
    SELECT
        cumulative.*,
        LAG(SOURCE_CUMULATIVE_CASES) OVER (
            PARTITION BY CANONICAL_ISO3 ORDER BY REPORT_DATE
        ) AS PREVIOUS_CUMULATIVE_CASES,
        LAG(SOURCE_CUMULATIVE_DEATHS) OVER (
            PARTITION BY CANONICAL_ISO3 ORDER BY REPORT_DATE
        ) AS PREVIOUS_CUMULATIVE_DEATHS,
        LAG(REPORT_DATE) OVER (
            PARTITION BY CANONICAL_ISO3 ORDER BY REPORT_DATE
        ) AS PREVIOUS_REPORT_DATE
    FROM COVID_ANALYTICS.STAGING.JHU_COUNTRY_CUMULATIVE AS cumulative
)
SELECT
    SOURCE_COUNTRY_NAME,
    SOURCE_ISO2,
    CANONICAL_ISO2 AS ISO2,
    CANONICAL_ISO3 AS ISO3,
    COUNTRY_NAME,
    REPORT_DATE,
    IFF(
        PREVIOUS_CUMULATIVE_CASES IS NULL,
        SOURCE_CUMULATIVE_CASES,
        SOURCE_CUMULATIVE_CASES - PREVIOUS_CUMULATIVE_CASES
    ) AS DAILY_CASES,
    IFF(
        PREVIOUS_CUMULATIVE_DEATHS IS NULL,
        SOURCE_CUMULATIVE_DEATHS,
        SOURCE_CUMULATIVE_DEATHS - PREVIOUS_CUMULATIVE_DEATHS
    ) AS DAILY_DEATHS,
    SOURCE_CUMULATIVE_CASES,
    SOURCE_CUMULATIVE_DEATHS,
    IFF(
        PREVIOUS_CUMULATIVE_CASES IS NULL,
        SOURCE_CUMULATIVE_CASES,
        SOURCE_CUMULATIVE_CASES - PREVIOUS_CUMULATIVE_CASES
    ) < 0 AS HAS_NEGATIVE_CASE_CORRECTION,
    IFF(
        PREVIOUS_CUMULATIVE_DEATHS IS NULL,
        SOURCE_CUMULATIVE_DEATHS,
        SOURCE_CUMULATIVE_DEATHS - PREVIOUS_CUMULATIVE_DEATHS
    ) < 0 AS HAS_NEGATIVE_DEATH_CORRECTION,
    PREVIOUS_REPORT_DATE IS NULL AS IS_FIRST_OBSERVATION,
    PREVIOUS_REPORT_DATE IS NOT NULL
        AND DATEDIFF('DAY', PREVIOUS_REPORT_DATE, REPORT_DATE) != 1
        AS HAS_DATE_GAP,
    SELECTED_LOCATION_LEVEL,
    CASES_SOURCE_ROW_COUNT,
    CASES_NON_NULL_SOURCE_ROWS,
    DEATHS_SOURCE_ROW_COUNT,
    DEATHS_NON_NULL_SOURCE_ROWS,
    MAPPING_STATUS,
    'JHU'::VARCHAR(3) AS SOURCE_NAME
FROM LAGGED;

CREATE OR REPLACE VIEW
    COVID_ANALYTICS.STAGING.COVID_COUNTRY_DAILY_EXTENDED
AS
WITH ECDC_IDENTIFIED AS (
    SELECT
        ecdc.*,
        COALESCE(ecdc.COUNTRY_ISO3, code_map.COUNTRY_ISO3)
            AS CANONICAL_ISO3
    FROM COVID_ANALYTICS.STAGING.COVID_COUNTRY_DAILY AS ecdc
    LEFT JOIN COVID_ANALYTICS.STAGING.CANONICAL_COUNTRY_CODE_MAP AS code_map
        ON ecdc.COUNTRY_ISO2 = code_map.COUNTRY_ISO2
),
ECDC_IDENTITIES AS (
    SELECT
        CANONICAL_ISO3,
        LOCATION_KEY,
        COUNTRY,
        COUNTRY_ISO2,
        CANONICAL_ISO3 AS COUNTRY_ISO3,
        MAPPING_APPLIED,
        EXPECTED_POPULATION_MATCH
    FROM ECDC_IDENTIFIED
    WHERE CANONICAL_ISO3 IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY CANONICAL_ISO3
        ORDER BY REPORT_DATE DESC, COUNTRY
    ) = 1
),
JHU_FIRST_DATES AS (
    SELECT ISO3, MIN(REPORT_DATE) AS FIRST_JHU_DATE
    FROM COVID_ANALYTICS.STAGING.JHU_COUNTRY_DAILY
    GROUP BY ISO3
),
BOUNDARIES AS (
    SELECT
        jhu.ISO3,
        ecdc.LOCATION_KEY IS NOT NULL AS HAS_ECDC_HISTORY,
        CASE
            WHEN ecdc.LOCATION_KEY IS NULL THEN jhu.FIRST_JHU_DATE
            ELSE COALESCE(policy.JHU_START_DATE, DATE '2020-12-15')
        END AS JHU_START_DATE
    FROM JHU_FIRST_DATES AS jhu
    LEFT JOIN ECDC_IDENTITIES AS ecdc ON jhu.ISO3 = ecdc.CANONICAL_ISO3
    LEFT JOIN COVID_ANALYTICS.RAW.JHU_GEOGRAPHY_POLICY AS policy
        ON jhu.ISO3 = policy.CANONICAL_ISO3
       AND policy.IS_INCLUDED
),
ECDC_BASELINES AS (
    SELECT
        ecdc.CANONICAL_ISO3,
        ecdc.CASES_CUMULATIVE,
        ecdc.DEATHS_CUMULATIVE
    FROM ECDC_IDENTIFIED AS ecdc
    INNER JOIN BOUNDARIES AS boundary
        ON ecdc.CANONICAL_ISO3 = boundary.ISO3
    WHERE ecdc.REPORT_DATE < boundary.JHU_START_DATE
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY ecdc.CANONICAL_ISO3
        ORDER BY ecdc.REPORT_DATE DESC
    ) = 1
),
ECDC_ACCEPTED AS (
    SELECT
        ecdc.COUNTRY,
        ecdc.COUNTRY_ISO2,
        ecdc.CANONICAL_ISO3 AS COUNTRY_ISO3,
        ecdc.LOCATION_KEY,
        ecdc.REPORT_DATE,
        ecdc.NEW_CASES_RAW,
        ecdc.NEW_DEATHS_RAW,
        ecdc.CASES_CUMULATIVE,
        ecdc.DEATHS_CUMULATIVE,
        ecdc.HAS_NEGATIVE_CASE_CORRECTION,
        ecdc.HAS_NEGATIVE_DEATH_CORRECTION,
        ecdc.SOURCE_ROW_COUNT,
        ecdc.MAPPING_APPLIED,
        ecdc.EXPECTED_POPULATION_MATCH,
        'ECDC'::VARCHAR(4) AS SOURCE_NAME,
        'ECDC_BASELINE'::VARCHAR AS SERIES_SEGMENT,
        boundary.JHU_START_DATE,
        'COUNTRY'::VARCHAR AS SELECTED_LOCATION_LEVEL,
        CASE
            WHEN ecdc.MAPPING_APPLIED THEN 'EXPLICIT_MAPPING'
            WHEN ecdc.CANONICAL_ISO3 IS NOT NULL THEN 'MAPPED'
            ELSE 'UNMAPPED'
        END AS MAPPING_STATUS,
        ecdc.CASES_CUMULATIVE AS SOURCE_CUMULATIVE_CASES,
        ecdc.DEATHS_CUMULATIVE AS SOURCE_CUMULATIVE_DEATHS
    FROM ECDC_IDENTIFIED AS ecdc
    LEFT JOIN BOUNDARIES AS boundary
        ON ecdc.CANONICAL_ISO3 = boundary.ISO3
    WHERE boundary.ISO3 IS NULL
       OR ecdc.REPORT_DATE < boundary.JHU_START_DATE
),
JHU_ACCEPTED_BASE AS (
    SELECT
        COALESCE(ecdc.COUNTRY, jhu.COUNTRY_NAME) AS COUNTRY,
        COALESCE(ecdc.COUNTRY_ISO2, jhu.ISO2) AS COUNTRY_ISO2,
        jhu.ISO3 AS COUNTRY_ISO3,
        COALESCE(ecdc.LOCATION_KEY, jhu.ISO3) AS LOCATION_KEY,
        jhu.REPORT_DATE,
        jhu.DAILY_CASES AS NEW_CASES_RAW,
        jhu.DAILY_DEATHS AS NEW_DEATHS_RAW,
        boundary.HAS_ECDC_HISTORY,
        baseline.CASES_CUMULATIVE AS ECDC_BASELINE_CASES,
        baseline.DEATHS_CUMULATIVE AS ECDC_BASELINE_DEATHS,
        jhu.SOURCE_CUMULATIVE_CASES,
        jhu.SOURCE_CUMULATIVE_DEATHS,
        jhu.HAS_NEGATIVE_CASE_CORRECTION,
        jhu.HAS_NEGATIVE_DEATH_CORRECTION,
        GREATEST(
            jhu.CASES_SOURCE_ROW_COUNT,
            jhu.DEATHS_SOURCE_ROW_COUNT
        ) AS SOURCE_ROW_COUNT,
        jhu.MAPPING_STATUS != 'MAPPED' AS MAPPING_APPLIED,
        population.COUNTRY_CODE_ISO3 IS NOT NULL AS EXPECTED_POPULATION_MATCH,
        boundary.JHU_START_DATE,
        jhu.SELECTED_LOCATION_LEVEL,
        jhu.MAPPING_STATUS
    FROM COVID_ANALYTICS.STAGING.JHU_COUNTRY_DAILY AS jhu
    INNER JOIN BOUNDARIES AS boundary ON jhu.ISO3 = boundary.ISO3
    LEFT JOIN ECDC_IDENTITIES AS ecdc ON jhu.ISO3 = ecdc.CANONICAL_ISO3
    LEFT JOIN ECDC_BASELINES AS baseline
        ON jhu.ISO3 = baseline.CANONICAL_ISO3
    LEFT JOIN COVID_ANALYTICS.RAW.WORLD_BANK_POPULATION_2020 AS population
        ON jhu.ISO3 = population.COUNTRY_CODE_ISO3
    WHERE jhu.REPORT_DATE >= boundary.JHU_START_DATE
),
JHU_ACCEPTED AS (
    SELECT
        COUNTRY,
        COUNTRY_ISO2,
        COUNTRY_ISO3,
        LOCATION_KEY,
        REPORT_DATE,
        NEW_CASES_RAW,
        NEW_DEATHS_RAW,
        IFF(
            HAS_ECDC_HISTORY,
            ECDC_BASELINE_CASES + SUM(NEW_CASES_RAW) OVER (
                PARTITION BY COUNTRY_ISO3
                ORDER BY REPORT_DATE
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ),
            SOURCE_CUMULATIVE_CASES
        ) AS CASES_CUMULATIVE,
        IFF(
            HAS_ECDC_HISTORY,
            ECDC_BASELINE_DEATHS + SUM(NEW_DEATHS_RAW) OVER (
                PARTITION BY COUNTRY_ISO3
                ORDER BY REPORT_DATE
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ),
            SOURCE_CUMULATIVE_DEATHS
        ) AS DEATHS_CUMULATIVE,
        HAS_NEGATIVE_CASE_CORRECTION,
        HAS_NEGATIVE_DEATH_CORRECTION,
        SOURCE_ROW_COUNT,
        MAPPING_APPLIED,
        EXPECTED_POPULATION_MATCH,
        'JHU'::VARCHAR(4) AS SOURCE_NAME,
        IFF(
            HAS_ECDC_HISTORY,
            'JHU_CONTINUATION',
            'JHU_ONLY'
        )::VARCHAR AS SERIES_SEGMENT,
        JHU_START_DATE,
        SELECTED_LOCATION_LEVEL,
        MAPPING_STATUS,
        SOURCE_CUMULATIVE_CASES,
        SOURCE_CUMULATIVE_DEATHS
    FROM JHU_ACCEPTED_BASE
)
SELECT * FROM ECDC_ACCEPTED
UNION ALL
SELECT * FROM JHU_ACCEPTED;

CREATE OR REPLACE VIEW
    COVID_ANALYTICS.MARTS.CASE_INCREASE_PATTERNS_EXTENDED
AS
SELECT *
FROM COVID_ANALYTICS.STAGING.COVID_COUNTRY_DAILY_EXTENDED
MATCH_RECOGNIZE (
    PARTITION BY
        LOCATION_KEY,
        COUNTRY,
        COUNTRY_ISO2,
        COUNTRY_ISO3,
        SERIES_SEGMENT
    ORDER BY REPORT_DATE
    MEASURES
        MATCH_NUMBER() AS MATCH_NUMBER,
        FIRST(REPORT_DATE) AS START_DATE,
        LAST(REPORT_DATE) AS END_DATE,
        COUNT(*) AS DAYS_IN_PATTERN,
        COUNT(INCREASE_DAY.*) AS CONSECUTIVE_INCREASES,
        FIRST(NEW_CASES_RAW) AS START_CASES,
        LAST(NEW_CASES_RAW) AS END_CASES
    ONE ROW PER MATCH
    AFTER MATCH SKIP PAST LAST ROW
    PATTERN (START_DAY INCREASE_DAY{3,})
    DEFINE
        START_DAY AS TRUE,
        INCREASE_DAY AS NEW_CASES_RAW > LAG(NEW_CASES_RAW)
            AND DATEDIFF('DAY', LAG(REPORT_DATE), REPORT_DATE) = 1
);

CREATE OR REPLACE TRANSIENT TABLE
    COVID_ANALYTICS.MARTS.COUNTRY_COVID_DENOMINATOR_EXTENDED
AS
WITH REQUIRED_COUNTRIES AS (
    SELECT DISTINCT COUNTRY_ISO3 AS ISO3
    FROM COVID_ANALYTICS.STAGING.COVID_COUNTRY_DAILY_EXTENDED
    WHERE COUNTRY_ISO3 IS NOT NULL
),
CANDIDATES AS (
    SELECT
        legacy.COUNTRY_CODE_ISO2 AS ISO2,
        legacy.COUNTRY_CODE_ISO3 AS ISO3,
        legacy.COUNTRY_NAME,
        legacy.POPULATION AS COVID_RATE_POPULATION_2020,
        legacy.POPULATION_YEAR,
        'legacy-world-bank-population-2020'::VARCHAR AS SOURCE_SNAPSHOT_ID,
        'v1-extended-candidate'::VARCHAR AS DENOMINATOR_VERSION,
        'legacy_2020_population_parallel_candidate'::VARCHAR
            AS DENOMINATOR_POLICY,
        TRUE AS IS_FROZEN,
        NULL::TIMESTAMP_TZ AS APPROVED_AT,
        'CANDIDATE'::VARCHAR AS DENOMINATOR_PUBLICATION_STATUS
    FROM REQUIRED_COUNTRIES AS required
    INNER JOIN COVID_ANALYTICS.RAW.WORLD_BANK_POPULATION_2020 AS legacy
        ON required.ISO3 = legacy.COUNTRY_CODE_ISO3
    WHERE NOT EXISTS (
        SELECT 1
        FROM COVID_ANALYTICS.MARTS.COUNTRY_COVID_DENOMINATOR AS approved
        WHERE approved.ISO3 = required.ISO3
    )
)
SELECT
    approved.*,
    'ACTIVE'::VARCHAR AS DENOMINATOR_PUBLICATION_STATUS
FROM COVID_ANALYTICS.MARTS.COUNTRY_COVID_DENOMINATOR AS approved
UNION ALL
SELECT * FROM CANDIDATES;

CREATE OR REPLACE VIEW
    COVID_ANALYTICS.MARTS.COVID_ENRICHED_EXTENDED
AS
SELECT
    covid.COUNTRY,
    COALESCE(covid.COUNTRY_ISO2, denominator.ISO2) AS COUNTRY_ISO2,
    COALESCE(covid.COUNTRY_ISO3, denominator.ISO3) AS COUNTRY_ISO3,
    covid.LOCATION_KEY,
    covid.REPORT_DATE,
    covid.NEW_CASES_RAW,
    covid.NEW_DEATHS_RAW,
    covid.CASES_CUMULATIVE,
    covid.DEATHS_CUMULATIVE,
    denominator.COUNTRY_NAME AS DENOMINATOR_COUNTRY_NAME,
    denominator.COVID_RATE_POPULATION_2020,
    denominator.POPULATION_YEAR AS COVID_RATE_POPULATION_YEAR,
    denominator.SOURCE_SNAPSHOT_ID AS DENOMINATOR_SOURCE_SNAPSHOT_ID,
    denominator.DENOMINATOR_VERSION,
    denominator.DENOMINATOR_POLICY,
    denominator.IS_FROZEN AS DENOMINATOR_IS_FROZEN,
    denominator.DENOMINATOR_PUBLICATION_STATUS,
    ROUND(
        covid.NEW_CASES_RAW
        / NULLIF(denominator.COVID_RATE_POPULATION_2020, 0) * 100000,
        2
    ) AS NEW_CASES_PER_100K,
    ROUND(
        covid.NEW_DEATHS_RAW
        / NULLIF(denominator.COVID_RATE_POPULATION_2020, 0) * 100000,
        2
    ) AS NEW_DEATHS_PER_100K,
    ROUND(
        covid.CASES_CUMULATIVE
        / NULLIF(denominator.COVID_RATE_POPULATION_2020, 0) * 100000,
        2
    ) AS CASES_PER_100K,
    ROUND(
        covid.DEATHS_CUMULATIVE
        / NULLIF(denominator.COVID_RATE_POPULATION_2020, 0) * 100000,
        2
    ) AS DEATHS_PER_100K,
    ROUND(
        covid.DEATHS_CUMULATIVE
        / NULLIF(covid.CASES_CUMULATIVE, 0) * 100,
        4
    ) AS MORTALITY_RATE_PERCENT,
    CASE
        WHEN denominator.DENOMINATOR_PUBLICATION_STATUS = 'CANDIDATE'
            THEN 'MATCHED_CANDIDATE'
        WHEN denominator.COVID_RATE_POPULATION_2020 IS NOT NULL THEN 'MATCHED'
        WHEN NOT covid.EXPECTED_POPULATION_MATCH THEN 'SOURCE_UNAVAILABLE'
        WHEN covid.COUNTRY_ISO2 IS NULL AND covid.COUNTRY_ISO3 IS NULL
            THEN 'NO_ISO_CODE'
        ELSE 'UNMATCHED'
    END AS DENOMINATOR_JOIN_STATUS,
    covid.HAS_NEGATIVE_CASE_CORRECTION,
    covid.HAS_NEGATIVE_DEATH_CORRECTION,
    covid.MAPPING_APPLIED,
    covid.SOURCE_ROW_COUNT,
    covid.SOURCE_NAME,
    covid.SERIES_SEGMENT,
    covid.JHU_START_DATE,
    covid.SELECTED_LOCATION_LEVEL,
    covid.MAPPING_STATUS,
    covid.SOURCE_CUMULATIVE_CASES,
    covid.SOURCE_CUMULATIVE_DEATHS
FROM COVID_ANALYTICS.STAGING.COVID_COUNTRY_DAILY_EXTENDED AS covid
LEFT JOIN COVID_ANALYTICS.MARTS.COUNTRY_COVID_DENOMINATOR_EXTENDED AS denominator
    ON covid.COUNTRY_ISO3 = denominator.ISO3
    OR (
        covid.COUNTRY_ISO3 IS NULL
        AND covid.COUNTRY_ISO2 = denominator.ISO2
    );

CREATE OR REPLACE TRANSIENT TABLE
    COVID_ANALYTICS.MARTS.COUNTRY_LATEST_METRICS_EXTENDED
AS
SELECT
    LOCATION_KEY,
    COUNTRY,
    COUNTRY_ISO2,
    COUNTRY_ISO3,
    REPORT_DATE,
    COVID_RATE_POPULATION_2020,
    COVID_RATE_POPULATION_YEAR,
    DENOMINATOR_SOURCE_SNAPSHOT_ID,
    DENOMINATOR_VERSION,
    DENOMINATOR_POLICY,
    DENOMINATOR_IS_FROZEN,
    DENOMINATOR_PUBLICATION_STATUS,
    CASES_CUMULATIVE,
    DEATHS_CUMULATIVE,
    CASES_PER_100K,
    DEATHS_PER_100K,
    MORTALITY_RATE_PERCENT,
    DENOMINATOR_JOIN_STATUS,
    SOURCE_NAME,
    SERIES_SEGMENT,
    JHU_START_DATE,
    SELECTED_LOCATION_LEVEL,
    MAPPING_STATUS,
    SOURCE_CUMULATIVE_CASES,
    SOURCE_CUMULATIVE_DEATHS
FROM COVID_ANALYTICS.MARTS.COVID_ENRICHED_EXTENDED
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY LOCATION_KEY
    ORDER BY REPORT_DATE DESC
) = 1;

CREATE OR REPLACE TRANSIENT TABLE
    COVID_ANALYTICS.APP.ECDC_JHU_OVERLAP_AUDIT
AS
WITH ECDC_IDENTIFIED AS (
    SELECT
        COALESCE(ecdc.COUNTRY_ISO3, code_map.COUNTRY_ISO3) AS ISO3,
        COALESCE(ecdc.COUNTRY_ISO2, code_map.COUNTRY_ISO2) AS ISO2,
        ecdc.COUNTRY AS COUNTRY_NAME,
        ecdc.REPORT_DATE,
        ecdc.NEW_CASES_RAW AS ECDC_DAILY_CASES,
        ecdc.NEW_DEATHS_RAW AS ECDC_DAILY_DEATHS,
        ecdc.CASES_CUMULATIVE AS ECDC_CUMULATIVE_CASES,
        ecdc.DEATHS_CUMULATIVE AS ECDC_CUMULATIVE_DEATHS
    FROM COVID_ANALYTICS.STAGING.COVID_COUNTRY_DAILY AS ecdc
    LEFT JOIN COVID_ANALYTICS.STAGING.CANONICAL_COUNTRY_CODE_MAP AS code_map
        ON ecdc.COUNTRY_ISO2 = code_map.COUNTRY_ISO2
    WHERE COALESCE(ecdc.COUNTRY_ISO3, code_map.COUNTRY_ISO3) IS NOT NULL
),
OVERLAP_BOUNDS AS (
    SELECT
        (SELECT MIN(REPORT_DATE)
         FROM COVID_ANALYTICS.STAGING.JHU_COUNTRY_DAILY) AS FIRST_DATE,
        (SELECT MAX(REPORT_DATE)
         FROM ECDC_IDENTIFIED) AS LAST_DATE
),
ECDC_OVERLAP AS (
    SELECT ecdc.*
    FROM ECDC_IDENTIFIED AS ecdc
    CROSS JOIN OVERLAP_BOUNDS AS bounds
    WHERE ecdc.REPORT_DATE BETWEEN bounds.FIRST_DATE AND bounds.LAST_DATE
),
JHU_OVERLAP AS (
    SELECT jhu.*
    FROM COVID_ANALYTICS.STAGING.JHU_COUNTRY_DAILY AS jhu
    CROSS JOIN OVERLAP_BOUNDS AS bounds
    WHERE jhu.REPORT_DATE BETWEEN bounds.FIRST_DATE AND bounds.LAST_DATE
)
SELECT
    COALESCE(ecdc.ISO2, jhu.ISO2) AS ISO2,
    COALESCE(ecdc.ISO3, jhu.ISO3) AS ISO3,
    COALESCE(ecdc.COUNTRY_NAME, jhu.COUNTRY_NAME) AS COUNTRY_NAME,
    COALESCE(ecdc.REPORT_DATE, jhu.REPORT_DATE) AS REPORT_DATE,
    CASE
        WHEN ecdc.ISO3 IS NOT NULL AND jhu.ISO3 IS NOT NULL THEN 'BOTH'
        WHEN ecdc.ISO3 IS NOT NULL THEN 'ECDC_ONLY'
        ELSE 'JHU_ONLY'
    END AS MATCH_STATUS,
    ecdc.ECDC_DAILY_CASES,
    jhu.DAILY_CASES AS JHU_DAILY_CASES,
    ecdc.ECDC_DAILY_DEATHS,
    jhu.DAILY_DEATHS AS JHU_DAILY_DEATHS,
    ecdc.ECDC_CUMULATIVE_CASES,
    jhu.SOURCE_CUMULATIVE_CASES AS JHU_CUMULATIVE_CASES,
    ecdc.ECDC_CUMULATIVE_DEATHS,
    jhu.SOURCE_CUMULATIVE_DEATHS AS JHU_CUMULATIVE_DEATHS,
    ecdc.ECDC_DAILY_CASES - jhu.DAILY_CASES AS DAILY_CASE_DIFFERENCE,
    ABS(ecdc.ECDC_DAILY_CASES - jhu.DAILY_CASES)
        AS ABS_DAILY_CASE_DIFFERENCE,
    ecdc.ECDC_DAILY_DEATHS - jhu.DAILY_DEATHS AS DAILY_DEATH_DIFFERENCE,
    ABS(ecdc.ECDC_DAILY_DEATHS - jhu.DAILY_DEATHS)
        AS ABS_DAILY_DEATH_DIFFERENCE,
    ecdc.ECDC_CUMULATIVE_CASES - jhu.SOURCE_CUMULATIVE_CASES
        AS CUMULATIVE_CASE_DIFFERENCE,
    ecdc.ECDC_CUMULATIVE_DEATHS - jhu.SOURCE_CUMULATIVE_DEATHS
        AS CUMULATIVE_DEATH_DIFFERENCE
FROM ECDC_OVERLAP AS ecdc
FULL OUTER JOIN JHU_OVERLAP AS jhu
    ON ecdc.ISO3 = jhu.ISO3
   AND ecdc.REPORT_DATE = jhu.REPORT_DATE;

-- Compact release evidence. Bootstrap applies the corresponding postconditions.
SELECT
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT ISO3) AS COUNTRY_COUNT,
    MIN(REPORT_DATE) AS FIRST_DATE,
    MAX(REPORT_DATE) AS LAST_DATE,
    COUNT_IF(ISO3 IS NULL) AS NULL_ISO3_ROWS,
    COUNT_IF(HAS_DATE_GAP) AS DATE_GAP_ROWS,
    COUNT_IF(HAS_NEGATIVE_CASE_CORRECTION) AS NEGATIVE_CASE_CORRECTIONS,
    COUNT_IF(HAS_NEGATIVE_DEATH_CORRECTION) AS NEGATIVE_DEATH_CORRECTIONS
FROM COVID_ANALYTICS.STAGING.JHU_COUNTRY_DAILY;

SELECT
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT LOCATION_KEY) AS LOCATION_COUNT,
    COUNT_IF(SERIES_SEGMENT = 'ECDC_BASELINE') AS ECDC_ROWS,
    COUNT_IF(SERIES_SEGMENT = 'JHU_ONLY') AS JHU_ONLY_ROWS,
    MIN(REPORT_DATE) AS FIRST_DATE,
    MAX(REPORT_DATE) AS LAST_DATE
FROM COVID_ANALYTICS.STAGING.COVID_COUNTRY_DAILY_EXTENDED;

SELECT
    COUNT(*) AS PATTERN_COUNT,
    COUNT(DISTINCT LOCATION_KEY) AS LOCATION_COUNT,
    MIN(START_DATE) AS FIRST_PATTERN_DATE,
    MAX(END_DATE) AS LAST_PATTERN_DATE,
    COUNT_IF(DAYS_IN_PATTERN != CONSECUTIVE_INCREASES + 1)
        AS INVALID_DURATION_ROWS,
    COUNT_IF(CONSECUTIVE_INCREASES < 3) AS INVALID_INCREASE_ROWS
FROM COVID_ANALYTICS.MARTS.CASE_INCREASE_PATTERNS_EXTENDED;

SELECT
    MATCH_STATUS,
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT ISO3) AS COUNTRY_COUNT
FROM COVID_ANALYTICS.APP.ECDC_JHU_OVERLAP_AUDIT
GROUP BY MATCH_STATUS
ORDER BY MATCH_STATUS;
